services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=True
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=recipe_db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipe_db
    
volumes:
  dev-db-data:
