services:
  
  app:
    build: 
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_NAME=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      # ports:
      # - "5432:5432" 

  proxy:
    build: 
      context: .
      dockerfile: Dockerfile-proxy
    restart: always
    ports:
      - "8008:8000"
    environment:
    depends_on:
      - app
    volumes:
      - static-data:/vol/static
  volumes:
    postgres-data:
    static-data:
