# Generated by Django 3.2.25 on 2025-03-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient_recipe_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
