# Generated by Django 3.2.25 on 2025-03-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='status_code',
        ),
    ]
