name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Build Docker image
        run: docker compose build 

      - name: Ensure database directory exists
        run: |
          mkdir -p ./app/data
          touch ./app/data/db.sqlite3

      - name: Fix database permissions
        run: |
          sudo chmod -R 777 ./app/data
          sudo chown -R $USER:$USER ./app/data
      
      - name: Run migrations  
        run: docker compose run --rm app python manage.py migrate

      - name: Install dependencies  
        run: docker compose run --rm app pip install -r ./requirements.txt  

      - name: Run tests
        run: docker compose run --rm app python manage.py test

      - name: Run linting
        run: docker compose run --rm app flake8
