---
name: Checks
- name: Install dependencies
  run: pip install -r requirements.txt

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-20.04
    steps:
      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERTOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
