---
name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test & Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker & Install Docker Compose  # ✅ Ensure Docker Compose is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Build Docker image
        run: docker-compose build 

      - name: Start Docker containers 
        run: docker-compose up -d  

      - name: Install dependencies  
        run: docker-compose exec -T app pip install -r requirements.txt  

      - name: Run migrations  
        run: docker-compose exec -T app python manage.py migrate

      - name: Run tests
        run: docker-compose exec -T app python manage.py test

      - name: Run linting
        run: docker-compose exec -T app flake8
